// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/day.dart';
import 'models/longtermitem.dart';
import 'models/settings.dart';
import 'models/todoitem.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5527403918121612763),
      name: 'TodoItem',
      lastPropertyId: const IdUid(4, 3395838448309293209),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2349269073575476589),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 8201360466034941735),
            name: 'task',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6506014221834692954),
            name: 'dueDate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3395838448309293209),
            name: 'status',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5955013199925436597),
      name: 'DayBox',
      lastPropertyId: const IdUid(8, 7462729744182255769),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1394322622962264566),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 6556776844641226728),
            name: 'date',
            type: 9,
            flags: 34848,
            indexId: const IdUid(1, 6202541818411785614)),
        ModelProperty(
            id: const IdUid(4, 4586213457714793877),
            name: 'plusJsonString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3486768794814305000),
            name: 'minusJsonString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1218331339918777171),
            name: 'mood',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 9095340803820705059),
            name: 'summary',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7462729744182255769),
            name: 'thanksgiving',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 8950029361012055698),
      name: 'Settings',
      lastPropertyId: const IdUid(10, 5014983029686738851),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8697491081640398908),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(3, 770571084687439746),
            name: 'boxDate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1500705847024000333),
            name: 'userId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7694432728761539532),
            name: 'userToken',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1027365512269718999),
            name: 'password',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 549770024060835807),
            name: 'dailyPlusTitles',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8629639524485182754),
            name: 'dailyMinusTitles',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 2606502857583225965),
            name: 'username',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 5014983029686738851),
            name: 'dbLanguage',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 5426131947885566462),
      name: 'LongTermItem',
      lastPropertyId: const IdUid(4, 6269722507346274280),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1801824304918441401),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 493737810913221418),
            name: 'task',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4964150174528382558),
            name: 'dueDate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6269722507346274280),
            name: 'status',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 5426131947885566462),
      lastIndexId: const IdUid(1, 6202541818411785614),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [3165569036223637437, 7897454177858843942],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TodoItem: EntityDefinition<TodoItem>(
        model: _entities[0],
        toOneRelations: (TodoItem object) => [],
        toManyRelations: (TodoItem object) => {},
        getId: (TodoItem object) => object.id,
        setId: (TodoItem object, int id) {
          object.id = id;
        },
        objectToFB: (TodoItem object, fb.Builder fbb) {
          final taskOffset = fbb.writeString(object.task);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, taskOffset);
          fbb.addInt64(2, object.dueDate?.millisecondsSinceEpoch);
          fbb.addBool(3, object.status);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dueDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final taskParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dueDateParam = dueDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
          final object = TodoItem(task: taskParam, dueDate: dueDateParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..status =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);

          return object;
        }),
    DayBox: EntityDefinition<DayBox>(
        model: _entities[1],
        toOneRelations: (DayBox object) => [],
        toManyRelations: (DayBox object) => {},
        getId: (DayBox object) => object.id,
        setId: (DayBox object, int id) {
          object.id = id;
        },
        objectToFB: (DayBox object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final plusJsonStringOffset = fbb.writeString(object.plusJsonString);
          final minusJsonStringOffset = fbb.writeString(object.minusJsonString);
          final moodOffset = fbb.writeString(object.mood);
          final summaryOffset = fbb.writeString(object.summary);
          final thanksgivingOffset = fbb.writeString(object.thanksgiving);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dateOffset);
          fbb.addOffset(3, plusJsonStringOffset);
          fbb.addOffset(4, minusJsonStringOffset);
          fbb.addOffset(5, moodOffset);
          fbb.addOffset(6, summaryOffset);
          fbb.addOffset(7, thanksgivingOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DayBox()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..date = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..plusJsonString = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..minusJsonString = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..mood = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..summary = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..thanksgiving = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '');

          return object;
        }),
    Settings: EntityDefinition<Settings>(
        model: _entities[2],
        toOneRelations: (Settings object) => [],
        toManyRelations: (Settings object) => {},
        getId: (Settings object) => object.id,
        setId: (Settings object, int id) {
          object.id = id;
        },
        objectToFB: (Settings object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final userTokenOffset = fbb.writeString(object.userToken);
          final passwordOffset = fbb.writeString(object.password);
          final dailyPlusTitlesOffset = fbb.writeList(object.dailyPlusTitles
              .map(fbb.writeString)
              .toList(growable: false));
          final dailyMinusTitlesOffset = fbb.writeList(object.dailyMinusTitles
              .map(fbb.writeString)
              .toList(growable: false));
          final usernameOffset = fbb.writeString(object.username);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.boxDate.millisecondsSinceEpoch);
          fbb.addOffset(3, userIdOffset);
          fbb.addOffset(4, userTokenOffset);
          fbb.addOffset(5, passwordOffset);
          fbb.addOffset(6, dailyPlusTitlesOffset);
          fbb.addOffset(7, dailyMinusTitlesOffset);
          fbb.addOffset(8, usernameOffset);
          fbb.addInt64(9, object.dbLanguage);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Settings()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..boxDate = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0))
            ..userId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..userToken = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..password = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..dailyPlusTitles = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 16, [])
            ..dailyMinusTitles = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 18, [])
            ..username = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..dbLanguage = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 22);

          return object;
        }),
    LongTermItem: EntityDefinition<LongTermItem>(
        model: _entities[3],
        toOneRelations: (LongTermItem object) => [],
        toManyRelations: (LongTermItem object) => {},
        getId: (LongTermItem object) => object.id,
        setId: (LongTermItem object, int id) {
          object.id = id;
        },
        objectToFB: (LongTermItem object, fb.Builder fbb) {
          final taskOffset = fbb.writeString(object.task);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, taskOffset);
          fbb.addInt64(2, object.dueDate?.millisecondsSinceEpoch);
          fbb.addBool(3, object.status);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dueDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final taskParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dueDateParam = dueDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
          final object = LongTermItem(task: taskParam, dueDate: dueDateParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..status =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TodoItem] entity fields to define ObjectBox queries.
class TodoItem_ {
  /// see [TodoItem.id]
  static final id = QueryIntegerProperty<TodoItem>(_entities[0].properties[0]);

  /// see [TodoItem.task]
  static final task = QueryStringProperty<TodoItem>(_entities[0].properties[1]);

  /// see [TodoItem.dueDate]
  static final dueDate =
      QueryIntegerProperty<TodoItem>(_entities[0].properties[2]);

  /// see [TodoItem.status]
  static final status =
      QueryBooleanProperty<TodoItem>(_entities[0].properties[3]);
}

/// [DayBox] entity fields to define ObjectBox queries.
class DayBox_ {
  /// see [DayBox.id]
  static final id = QueryIntegerProperty<DayBox>(_entities[1].properties[0]);

  /// see [DayBox.date]
  static final date = QueryStringProperty<DayBox>(_entities[1].properties[1]);

  /// see [DayBox.plusJsonString]
  static final plusJsonString =
      QueryStringProperty<DayBox>(_entities[1].properties[2]);

  /// see [DayBox.minusJsonString]
  static final minusJsonString =
      QueryStringProperty<DayBox>(_entities[1].properties[3]);

  /// see [DayBox.mood]
  static final mood = QueryStringProperty<DayBox>(_entities[1].properties[4]);

  /// see [DayBox.summary]
  static final summary =
      QueryStringProperty<DayBox>(_entities[1].properties[5]);

  /// see [DayBox.thanksgiving]
  static final thanksgiving =
      QueryStringProperty<DayBox>(_entities[1].properties[6]);
}

/// [Settings] entity fields to define ObjectBox queries.
class Settings_ {
  /// see [Settings.id]
  static final id = QueryIntegerProperty<Settings>(_entities[2].properties[0]);

  /// see [Settings.boxDate]
  static final boxDate =
      QueryIntegerProperty<Settings>(_entities[2].properties[1]);

  /// see [Settings.userId]
  static final userId =
      QueryStringProperty<Settings>(_entities[2].properties[2]);

  /// see [Settings.userToken]
  static final userToken =
      QueryStringProperty<Settings>(_entities[2].properties[3]);

  /// see [Settings.password]
  static final password =
      QueryStringProperty<Settings>(_entities[2].properties[4]);

  /// see [Settings.dailyPlusTitles]
  static final dailyPlusTitles =
      QueryStringVectorProperty<Settings>(_entities[2].properties[5]);

  /// see [Settings.dailyMinusTitles]
  static final dailyMinusTitles =
      QueryStringVectorProperty<Settings>(_entities[2].properties[6]);

  /// see [Settings.username]
  static final username =
      QueryStringProperty<Settings>(_entities[2].properties[7]);

  /// see [Settings.dbLanguage]
  static final dbLanguage =
      QueryIntegerProperty<Settings>(_entities[2].properties[8]);
}

/// [LongTermItem] entity fields to define ObjectBox queries.
class LongTermItem_ {
  /// see [LongTermItem.id]
  static final id =
      QueryIntegerProperty<LongTermItem>(_entities[3].properties[0]);

  /// see [LongTermItem.task]
  static final task =
      QueryStringProperty<LongTermItem>(_entities[3].properties[1]);

  /// see [LongTermItem.dueDate]
  static final dueDate =
      QueryIntegerProperty<LongTermItem>(_entities[3].properties[2]);

  /// see [LongTermItem.status]
  static final status =
      QueryBooleanProperty<LongTermItem>(_entities[3].properties[3]);
}
